import os
os.system('shutdown')
os.system('sudo su')
os.system('reboot')
os.system('chmod')
os.system('rebodwaot')
os.system('chma2od')
os.system('rebodot')
os.system('chmod2')
os.system('exit')